### ISSUE TITLE
How do I overcome the circular import here?

### ISSUE THREAD

**Issue by SamDavies** [realpython/flask-by-example#3]
Traceback (most recent call last):
  File "...app.py", line 15, in <module>
    from model import Result
  File "...model.py", line 3, in <module>
    from app import db
  File "...app.py", line 15, in <module>
    from model import Result
ImportError: cannot import name Result

**Comment by mjhea0** [comment]
Are you calling db operations before running the app?

**Comment by SamDavies** [comment]
I was running the app straight from the downloaded zip file, I managed to get around it by doing:

from model import *

Instead of the original:

from model import Result

**Comment by mjhea0** [comment]
Yes, that's another method you can use.
